/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratoriosiu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Langas
 */
public class Secciones_Josue_9959_18_4829 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Secciones_Josue_9959_18_4829
     */
    public Secciones_Josue_9959_18_4829() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Buscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Nombre_Secciones = new javax.swing.JTextField();
        jButton_Insertar = new javax.swing.JButton();
        jButton_Modificar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_Estatus_Secciones = new javax.swing.JTextField();
        jButton_Buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_Codigo_Secciones = new javax.swing.JTextField();
        label_status = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("Estatus Secciones");

        txt_Nombre_Secciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nombre_SeccionesActionPerformed(evt);
            }
        });

        jButton_Insertar.setText("Insertar");
        jButton_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertarActionPerformed(evt);
            }
        });

        jButton_Modificar.setText("Modificar");
        jButton_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModificarActionPerformed(evt);
            }
        });

        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingrese Codigo Secciones");

        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo Secciones");

        jLabel2.setText("Nombre Secciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Nombre_Secciones)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(txt_Codigo_Secciones)
                            .addComponent(txt_Estatus_Secciones))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jButton_Insertar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Modificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Eliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(label_status, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Buscar)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Codigo_Secciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(label_status, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Nombre_Secciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton_Insertar)
                    .addComponent(jButton_Modificar)
                    .addComponent(jButton_Eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Estatus_Secciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Buscar))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Nombre_SeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nombre_SeccionesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_Nombre_SeccionesActionPerformed

    private void jButton_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertarActionPerformed
        // TODO add your handling code here:

        try
        {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/SIU","root","Langas798");
            PreparedStatement pst = cn.prepareStatement("insert into Secciones values(?,?,?)");

            pst.setString(1, txt_Codigo_Secciones.getText().trim());
            pst.setString(2, txt_Nombre_Secciones.getText().trim());
            pst.setString(3, txt_Estatus_Secciones.getText().trim());
            pst.executeUpdate();

            txt_Codigo_Secciones.setText("");
            txt_Nombre_Secciones.setText("");
            txt_Estatus_Secciones.setText("");
            label_status.setText("Registrado.");

        }catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_InsertarActionPerformed

    private void jButton_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarActionPerformed
        // TODO add your handling code here:

        try {
            String ID = txt_Buscar.getText().trim();

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/SIU", "root", "Langas798");
            PreparedStatement pst = cn.prepareStatement("update Secciones set codigo_secciones = ?,nombre_secciones = ?,  estatus_secciones = ? where Codigo_Cliente = " + ID);

            pst.setString(1, txt_Codigo_Secciones.getText().trim());
            pst.setString(2, txt_Nombre_Secciones.getText().trim());
            pst.setString(3, txt_Estatus_Secciones.getText().trim());
            pst.executeUpdate();

            label_status.setText("Modificación exitosa.");

        } catch (Exception e)
        {

        }
    }//GEN-LAST:event_jButton_ModificarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        // TODO add your handling code here:

        try
        {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/SIU", "root", "Langas798");
            PreparedStatement pst = cn.prepareStatement("delete from Secciones where codigo_secciones = ?");

            pst.setString(1, txt_Buscar.getText().trim());
            pst.executeUpdate();

            txt_Codigo_Secciones.setText("");
            txt_Nombre_Secciones.setText("");
            txt_Estatus_Secciones.setText("");

            label_status.setText("Registro eliminado.");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        // TODO add your handling code here:

        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/SIU", "root", "Langas798");
            PreparedStatement pst = cn.prepareStatement("select * from Secciones where Codigo_Secciones = ?");
            pst.setString(1, txt_Buscar.getText().trim());

            ResultSet rs = pst.executeQuery();

            if(rs.next())
            {
                txt_Codigo_Secciones.setText(rs.getString("codigo_secciones"));
                txt_Nombre_Secciones.setText(rs.getString("nombre_secciones"));
                txt_Estatus_Secciones.setText(rs.getString("estatus_secciones"));
            } else
            {
                JOptionPane.showMessageDialog(null, "Seccion no registrada.");
            }
        }catch (Exception e)
        {

        }
    }//GEN-LAST:event_jButton_BuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_Insertar;
    private javax.swing.JButton jButton_Modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label_status;
    private javax.swing.JTextField txt_Buscar;
    private javax.swing.JTextField txt_Codigo_Secciones;
    private javax.swing.JTextField txt_Estatus_Secciones;
    private javax.swing.JTextField txt_Nombre_Secciones;
    // End of variables declaration//GEN-END:variables
}
